---
- shell: |
    "{{makinastates_dest}}/bin/salt-call" --version 1>/dev/null 2>&1 &&\
       "{{makinastates_dest}}/bin/ansible" --version 1>/dev/null 2>&1
    echo ${?}
  name: "test makinastates presence"
  register: makinastates_presence
  tags: makinastates,makinastates_presence
- shell: |
     {%if makinastates_presence.stdout and makinastates_presence.stdout[-1] == '0'%}
     test -e "{{makinastates_dest}}/var/.first_highstate"
     echo ${?}
     {%else %}echo 1{% endif %}
  name: "test makinastates presence"
  register: makinastates_presence
  when: "makinastates_test_first_highstate"
  tags: makinastates,makinastates_presence
