---
# variable may be overidden from inventory (salt_pillar)
# see ansible/roles/makinastates_lxc_vars/defaults/main.yml
- hosts: "{{compute_node}}"
  roles: [{role: 'makinastates_lxc_create'}]

- hosts: "{{lxc_container_name}}"
  roles: [{role: makinastates, makinastates_nodetype: lxccontainer}]
