---
# variable may be overidden from inventory (salt_pillar)
# see ansible/roles/makinastates_lxc_vars/defaults/main.yml
- hosts: "{{compute_node}}"
  roles: [{role: 'makinastates_lxc_create'}]

- hosts: "{{lxc_container_name}}"
  roles: [{role: makinastates, makinastates_nodetype: lxccontainer}]
  vars:
    ansible_ssh_common_args: |
      -o ProxyCommand="ssh -W %h:%p -q {{hostvars[compute_node]['ansible_user']}}@{{hostvars[compute_node]['ansible_host']}} -p {{hostvars[compute_node]['ansible_port']}}"
