---
# variable may be overidden from inventory (salt_pillar)
# see ansible/roles/makinastates_lxc_vars/defaults/main.yml
# (see the 'all' statement, must be called with -l indicating the host(s) where
# to create such a container
- hosts: all
  roles: [{role: 'makinastates_lxc_create'}]

- hosts: "{{lxc_container_name}}"
  roles:
    - role: makinastates_presence
    - role: makinastates
      makinastates_nodetype: lxccontainer
      makinastates_version: "{{makinastates_lxc_vars.msg['makinastates_version']}}"
      when: "makinastates_presence.stdout != '0'"
    - role: makinastates_presence
      allow_duplicates: true
    - role: makinastates_reconfigure
      makinastates_minion_id: "{{lxc_container_name}}"
      makinastates_version: "{{makinastates_lxc_vars.msg['makinastates_version']}}"
      when: "makinastates_presence.stdout == '0'"
