---
# variable may be overidden from inventory (salt_pillar)
# see ansible/roles/makinastates_lxc_vars/defaults/main.yml
# (see the 'all' statement, must be called with -l indicating the host(s) where
# to create such a container
- hosts: all
  roles: [{role: 'makinastates_lxc_create'}]

- hosts: "{{lxc_container_name}}"
  tasks:
    - shell: |
        test -e /srv/makina-states/bin/salt-call
        test -e /srv/makina-states/bin/ansible
        echo $?
      name: "test makinastates presence"
      register: lxc_makinastates_presence

- hosts: "{{lxc_container_name}}"
  roles:
    - role: makinastates
      makinastates_nodetype: lxccontainer
      when: "lxc_makinastates_presence.stdout != '0'"

- hosts: "{{lxc_container_name}}"
  tasks:
    - name: test reconfiure makina-states
      shell: |
         grep -q "id: {{lxc_container_name}}" \
               /srv/makina-states/etc/salt/minion.d/01_local.conf
         echo $?
      when: "lxc_makinastates_presence.stdout == '0'"
      register: lxc_makinastates_reconfigured
    - name: reconfiure makina-states
      shell: |
        set -ex
        cd /srv/makina-states/
        git reset --hard HEAD
        /srv/makina-states/bin/boot-salt.sh -C --reconfigure -m {{lxc_container_name}} -n lxccontainer
      when: "lxc_makinastates_reconfigured.stdout != '0'"
