language: python
sudo: required
python: [2.7]
# 3 tests goals & achievments here:
# - install the standalone image (test the release artifacts & flags are in place)
# - smoke test the basic mastersalt/salt highstate
# - install the environment for further unit/integration tests
install: [sudo -E ./_scripts/travis_install.sh]
script: sudo -E ./_scripts/travis_test.sh
