language: python
python:
  - 2.7

# matrix:
install:
    - sudo apt-get install xz-utils python rsync acl
    - sudo python ./_scripts/install_prebuild_makina_states.py

script: sudo python _scripts/local_tests.py
