---
# execute a salt call on a host
- hosts: "{{hosts|default('all')}}"
  roles: [makinastates_pillar] 

- hosts: "{{hosts|default('all')}}"
  tasks:
    - name: >
            salt-call
            {{function|default('state.sls')}}
            {{saltargs|default('')}}
      saltcall: 
        function: "{{function|default('state.sls')}}" 
        args: "{{saltargs|default('')}}" 
