---
- name: "Synchronise {{lxc_container_name}} to {{inventory_hostname}} from {{lxc_orig_host}}"
  synchronize:
    src: '{{lxc_path}}/{{lxc_container_name}}/'
    dest: '{{lxc_path}}/{{lxc_container_name}}/'
    rsync_opts: ['-a', '-z', '-v', '--delete']
  delegate_to: "{{lxc_orig_host}}"
  tags: makinastates_lxc_sync
