---
- name: cloud - kvm installation
  saltcall: >
            function=state.sls
            args='makina-states.cloud.kvm.compute_node.install_kvm'
  tags: makinastates_cloud_cn,makinastates_cloud_cn_kvm
