---
- name: dnsconf
  saltcall: function=state.sls args='makina-states.cloud.generic.controller.dnsconf'
  tags: makinastates_controller_setup,makinastates_controller_dns

- name: generic cloud
  saltcall: function=state.sls args='makina-states.cloud.generic.controller.ssh'
  tags: makinastates_controller_setup,makinastates_controller_ssh
