---
- hosts: all
  tasks:
    - name: transfer script
      copy:
        mode: 755
        dest: "/sbin/whitelist_ips.sh"
        src: "../../../../files/sbin/whitelist_ips.sh"
    - name: "run supervision auth"
      shell: '/sbin/whitelist_ips.sh {{ip}}'
# VARIABLES:
#   - ip
