---
- name: install prerequisites
  apt: name={{item}} update_cache=yes
  with_items:
    - python
    - python-chardet
    - python3-chardet
    - git
    - curl
    - locales
    - language-pack-fr
    - language-pack-en
  tags: [makinastates, makinastates_setup]
