---
- name: reconfigure makina-states
  register: makinastates_presence/
  tags: makinastates,makinastates_reconfigure
  shell: |
    set -ex
    cd "{{makinastates_dest}}"
    if ! git diff --quiet --exit-code;then
      git stash || /bin/true
      git reset --hard HEAD
    fi
    if [ -e bin/boot-salt2.sh ];then
      sc="bin/boot-salt2.sh"
    else
      sc="bin/boot-salt.sh"
    fi
    "$sc" \
          {% if makinastates_nodetype %}-n "{{makinastates_nodetype}}" {% endif %} \
          {% if makinastates_minion_id %}-m "{{makinastates_minion_id}}" {% endif %}\
          {% if makinastates_version %}-b "{{makinastates_version}}" {% endif %}\
          {% if makinastates_salt_version %}--salt-branch "{{makinastates_salt_version}}" {% endif %}\
          {% if makinastates_ansible_version %}--ansible-branch "{{makinastates_ansible_version}}" {% endif %}\
          -C --reconfigure
