---
- name: lxc clone (from container)
  shell: "lxc-clone -o {{lxc_from_container}} -n {{lxc_container_name}} -B {{lxc_backing_store}}"
  when: 'makinastates_lxc_create_lxc_test.stdout != "0"'
  tags: makinastates_lxc_create,makinastates_lxc_create_lxc
