---
# we do not use anymore ansible/lxc_container
# - apt: name={{item}}
#   with_items:
#     - python-pip
#     - git
#     - build-essential
#     - python-dev
#     - lxc-dev
#   tags: makinastates_lxc_create,makinastates_lxc_create_prereq
# - pip:
#     name: "git+https://github.com/lxc/python2-lxc.git#egg=python2-lxc"
#     editable: true
#     executable: "{{lxc_pip}}"
#   tags: makinastates_lxc_create,makinastates_lxc_create_prereq
- copy:
    src: '~/.ssh/id_rsa.pub'
    dest: '/tmp/ansible_master.pub'
    mode: 644
  tags: makinastates_lxc_create
- debug:
    msg: {foo: "{{lxc_from_container}}"}
- name: lxc create test (from template script)
  shell: |
         lxc-ls --fancy |grep -v ^NAME|awk '{print $1}'|egrep -q "^{{lxc_container_name}}$";echo $?
  register: makinastates_lxc_create_lxc_test
  tags: makinastates_lxc_create,makinastates_lxc_create_lxc
- include: from_template.yml
  when: 'lxc_from_container == ""'
- include: from_image.yml
  when: 'lxc_from_container != ""'
- name: lxc config (from template script)
  template:
    src: "../templates/lxc.conf"
    dest: "{{lxc_path}}/{{lxc_container_name}}/config"
    mode: 600
  notify: "RestartContainer{{lxc_container_name}}"
  tags: makinastates_lxc_create,makinastates_lxc_create_lxc
- name: lxc mgmt scripts
  template:
    src: '../templates/{{item}}'
    dest: "{{lxc_path}}/{{lxc_container_name}}/{{item}}"
    mode: 755
  with_items:
    - init.sh
    - prereqs.sh
    - manage.sh
  tags: makinastates_lxc_create,makinastates_lxc_create_scripts
- name: "StartContainer{{lxc_container_name}}"
  shell: "{{lxc_path}}/{{lxc_container_name}}/manage.sh start"
  tags: makinastates_lxc_create,makinastates_lxc_create_prereq
- name: lxc prereq
  shell: "{{lxc_path}}/{{lxc_container_name}}/prereqs.sh"
  tags: makinastates_lxc_create,makinastates_lxc_create_prereq
- name: get ip
  shell: |
        lxc-attach -n {{lxc_container_name}} -- ip addr show eth0|grep inet|grep -v :|awk '{print $2}'|sed "s|/.*||g"
  register: makinastates_lxc_create_ip
  tags: makinastates_lxc_create,makinastates_lxc_create_ssh_key
- name: show ip
  debug: {msg: {eth0ip: "{{makinastates_lxc_create_ip}}"}}
# during bootstrap, connect to the container via the Bastion method
# and not via the iptables redirections
- add_host:
    name: "{{lxc_container_name}}"
    ansible_host: "{{makinastates_lxc_create_ip.stdout}}"
    ansible_port: 22
    ansible_ssh_common_args: |
      -o ProxyCommand="ssh -W %h:%p -q {{hostvars[compute_node]['ansible_user']}}@{{hostvars[compute_node]['ansible_host']}} -p {{hostvars[compute_node]['ansible_port']}}"
