---
- shell: "test -e /etc/makina-states;echo ${?}"
  register: makinastates_migv2_install_dir
  tags: makinastates_migv2,makinastates_migv2_setup
- name: setup
  shell: |
         set -ex
         if [ ! -e "{{makinastates_dest}}/.git" ];then
           git clone "{{makinastates_repo}}" -b "{{makinastates_version}}"\
             "{{makinastates_dest}}"
         fi
         cd /etc
         if [ -e makina-states/nodetype ] && [ ! -h makina-states/nodetype ];then
           cp -fv makina-states/nodetype {{makinastates_dest}}/etc/makina-states
         fi
         find mastersalt/makina-states salt/makina-states makina-states\
           -type f|\
           egrep ".(nodetype|yaml|jinja|json|pack)"|\
           egrep -v "(cloud|services|controllers|localsettings|nodetypes).yaml"|\
           while read f;do
             if [ ! -h $f ]; then
               cp -v $f {{makinastates_dest}}/etc/makina-states
               ln -sfv {{makinastates_dest}}/etc/makina-states/$(basename ${f}) ${f}
             fi
           done
         find mastersalt/makina-states salt/makina-states makina-states|\
           -type f|\
           egrep ".(nodetype|yaml|jinja|json|pack)"|\
           egrep "(cloud|services|controllers|localsettings|nodetypes).yaml"|\
           while read f;do
             if [ ! -h $f ]; then
               grep -i ": true" $f \
                 > {{makinastates_dest}}/etc/makina-states/$(basename $f)
               ln -sfv {{makinastates_dest}}/etc/makina-states/$(basename ${f}) ${f}
             fi
           done
  when: "makinastates_migv2_install_dir.stdout == '0'"
  tags: makinastates_migv2,makinastates_migv2_setup
