---
- copy: {src: '~/.ssh/id_rsa.pub', dest: '/tmp/ansible_master.pub',  mode: 644}
- include: from_template.yml
  when: bool(lxc_from_container) == False
- include: from_image.yml
  when: bool(lxc_from_container) == True
- lxc_container:
    container_ommands : |
      set -ex
      if [ ! -d /root/.ssh ];then mkdir -p /root/.ssh;fi
      if [ ! -e /root/.ssh/authorized_keys ];then touch /root/.ssh/authorized_keys;fi
      if lsb_release -i -s | egrep -iq "ubuntu|debian";then
        apt-get install -y python
      fi
- shell: |
      cat /tmp/ansible_master.pub | \
        lxc-attach -n {{lxc_container_name}} -- tee /root/.ssh/authorized_keys
