---
- name: "manual highstate on {{inventory_hostname}}"
  saltcall:
    function: state.sls
    args: makina-states.top
  register: makinastates_manualhighstate
  tags: [makinastates, makinastates_manualhighstate]
