---
- apt: name={{item}} update_cache=yes
  with_items:
    - python
    - git
    - curl
  tags: [makinastates_setup]

# download makina-states
- git: repo="{{makinastates_repo}}"
       dest="{{makinastates_dest}}"
       version="{{makinastates_version}}"
  tags: [makinastates_setup]

# run setup
- shell: "{{makinastates_dest}}/bin/boot-salt.sh -b {{makinastates_version}} -n {{makinastates_nodetype}}"
  tags: [makinastates_setup]

# test salt & ansible
- shell: bin/{{item}} --version
  args:
    chdir: "{{makinastates_dest}}"
  with_items:
    - salt-call
    - ansible
  tags: [makinastates_setup]
